#!/usr/bin/env perl

use strict;
use warnings;
use Mojolicious::Lite;
use Cpanel::JSON::XS;
use Path::Tiny;
use Net::Statsite::Client;

use Stor;

my $cfg = load_config();
my $statsite = Net::Statsite::Client->new(%{ $cfg->{statsite} });
my $stor = Stor->new(
    storage_pairs => $cfg->{storage_pairs},
    statsite      => $statsite,
);

get  '/'       => sub { $stor->about(@_)  };
get  '/status' => sub { $stor->status(@_) };
get  '/:sha'   => sub { $stor->get(@_)    };
post '/:sha'   => sub { $stor->post(@_)   };

app->secrets([$cfg->{secret}]);
app->start;


sub load_config {
    die 'CONFIG_FILE environment variable not set'
        if !defined $ENV{CONFIG_FILE};

    return decode_json(path($ENV{CONFIG_FILE})->slurp())
}
